global.status_update_character = "🟩";
global.leave_character = "🟨";
global.no_status_update_character = "🟥";
global.arrow_character = "▶"; // →➤
global.value_differentiating_character = ":";
global.repair_character = "🤖";
global.created_character = "➕";
global.done_character = "✅";
global.fail_character = "❌";
global.attended_character = "🟢";
global.not_attended_character = "🔴";
global.bot_command_initiator = "$";
global.backup_file_name = process.env.backup_file_name;
global.server_id = process.env.server_id;
global.status_updates_channels = process.env.status_updates_channels.split(",");
global.admin_commands_channels = process.env.admin_commands_channels.split(",");
global.logs_channels = process.env.logs_channels.split(",");
